permalink: /:year:month:day/:title
url: http://h01000110.github.io/windows-95
baseurl: /project

# variables
name: Yuma Tokunaga
description: An Economist for the U.S.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
